### PR TITLE
Add Pipfile with requirements

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by mayaCostantini** [comment]
/approve

Thanks @fridex !

**Comment by codificat** [comment]
/override aicoe-ci/build-check
although I don't think this will work... 

Future PRs to master should not get that context check now that there is a [local prow config](https://github.com/thoth-station/cli-examples/blob/c1eca65a633250124fd32a4107775224e9290d54/.prow.yaml#L1). A rebase here should also get rid of it. Or just use your powers to merge manually :smiley:

**Pull request merged**
